import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export default function TermsOfService() {
  return (
    <div className="container mx-auto py-8 px-4">
      <Card className="max-w-4xl mx-auto">
        <CardHeader>
          <CardTitle className="text-3xl font-bold">Terms of Service</CardTitle>
        </CardHeader>
        <CardContent className="space-y-8 md:p-6 p-3">
          <div className="space-y-4">
            <p className="text-lg leading-relaxed">
              Welcome to tempmailto.org. Please read the following terms
              carefully before using this website. By using the Site, you agree
              to the following terms and conditions.
            </p>
          </div>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">1. Use of Services</h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              tempmailto.org provides users with temporary email services. By
              using this service, you agree not to engage in any illegal or
              malicious activity. Additionally, you agree not to use this
              service beyond its intended scope or for any unauthorized
              purposes. The primary purpose of our service is to provide
              temporary and disposable email addresses to help protect your
              privacy and reduce spam in your primary inbox.
            </p>
            <p className="text-lg leading-relaxed">
              The temporary emails generated by tempmailto.org are valid for a
              limited period and can be used to receive verification emails,
              promotional offers, and other messages without sharing your
              personal email address. However, this service should not be used
              for illegal purposes, including but not limited to phishing,
              fraud, or any activity that violates laws and regulations.
            </p>
            <p className="text-lg leading-relaxed">
              We reserve the right to monitor the usage of our services to
              ensure compliance with these terms and to prevent misuse. Failure
              to adhere to these terms may result in the termination of access
              to our services.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">2. User Responsibility</h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              When using tempmailto.org, you are responsible for ensuring that
              the temporary email address you use does not compromise the
              security of your personal information. While we do not store your
              messages permanently, you are encouraged to avoid sharing
              sensitive or confidential information through our temporary email
              services.
            </p>
            <p className="text-lg leading-relaxed">
              Users should also refrain from using temporary email addresses for
              activities that could harm others or disrupt their services. This
              includes sending spam, creating fake accounts on other platforms,
              or engaging in deceptive practices.
            </p>
            <p className="text-lg leading-relaxed">
              If you discover any suspicious activity related to your use of our
              services, please report it immediately to our support team at
              admin@tempmailto.org.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">
              3. Intellectual Property Rights
            </h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              All content on tempmailto.org, including but not limited to text,
              graphics, logos, icons, and software, is the property of
              tempmailto.org or its content suppliers and is protected by
              copyright, trademark, and other intellectual property laws.
              Unauthorized use of our content is strictly prohibited.
            </p>
            <p className="text-lg leading-relaxed">
              You may not reproduce, distribute, or create derivative works
              based on our content without prior written consent from
              tempmailto.org. Any unauthorized use of our intellectual property
              will be subject to legal action.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">
              4. Privacy and Data Security
            </h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              tempmailto.org values your privacy and is committed to protecting
              your data. While we do not collect or store personal information,
              we may collect anonymized data, such as IP addresses and browser
              types, to improve our services. For more details, please refer to
              our Privacy Policy.
            </p>
            <p className="text-lg leading-relaxed">
              Our platform uses encryption and other security measures to
              protect the messages you receive. However, we cannot guarantee
              absolute security, and users should exercise caution when using
              our services.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">5. Changes to Services</h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              tempmailto.org reserves the right to modify, suspend, or
              discontinue any aspect of our services at any time without prior
              notice. While we strive to provide uninterrupted services, certain
              technical or operational issues may require temporary downtime.
            </p>
            <p className="text-lg leading-relaxed">
              We encourage users to stay updated on changes to our services by
              regularly visiting our website. Any changes to these terms will
              also be communicated through updates on this page.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">
              6. Termination of User Access
            </h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              tempmailto.org reserves the right to terminate or suspend user
              access at its sole discretion, with or without cause. Reasons for
              termination may include violations of these Terms of Service,
              misuse of our services, or any activity deemed harmful to the
              platform or other users.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">
              7. Disclaimer of Warranties
            </h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              tempmailto.org provides services on an "as is" and "as available"
              basis. We make no guarantees regarding the availability,
              reliability, or suitability of our services for any specific
              purpose. Use of our services is at your own risk.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">8. Contact Information</h2>
            <Separator className="my-2" />
            <p className="text-lg leading-relaxed">
              If you have any questions or concerns regarding these Terms of
              Service, please contact us at:
              <a
                href="mailto:admin@tempmailto.org"
                className="text-primary hover:underline font-medium"
              >
                admin@tempmailto.org
              </a>
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
}
